### ISSUE TITLE
Manage Rentals

### ISSUE THREAD

**Issue by Asimbong** [Asimbong/truckrentalsystem_backend#30]
CRUD operations like cancel/delete rental, update pickup or drop-off location ,pick-up time, change truck etc. These are done by the customer.

**Comment by Siyanda-m2** [comment]
okay ill be on it, the PC i was using is gone,ill try and use the work PC during lunch

**Comment by Asimbong** [comment]
Awe, can you please try to complete this by Sunday? We want to start with security, but we want to make sure that everything is working correctly.

**Comment by Siyanda-m2** [comment]
ill push on saturday

**Comment by Asimbong** [comment]
[like]  Asimbonge Mbende reacted to your message:
________________________________

**Comment by Siyanda-m2** [comment]
i have a few questions concerning the truck rental services class on the backend...it does not implement it's interface ...making it difficult any confusing to create(the response logic has to be hardcoded in the controller) and update a rental...can i change the rentTruck loggic on the backend -service and controler to be exact?  it will make my work very easy on the front end

**Comment by Siyanda-m2** [comment]
nvm i understand the logic now
