### ISSUE TITLE
Domain to Service Test

### ISSUE THREAD

**Issue by Asimbong** [Asimbong/truckrentalsystem_backend#8]
Please do Login and stop at service test.TruckType is also your class but it has already been done so you will take it from controllers.

**Comment by Siyanda-m2** [comment]
okay i will do so...i have an issue though ,i went to the labs and found them doing maintainance ,been trying to use the ones at e-learning to no avail. can i commit the ones from before,granted id have to change the package name?

**Comment by Asimbong** [comment]
Ok
________________________________
